language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode

jdk:
  - oraclejdk7

before_install:
  - wget https://github.com/downloads/lomereiter/sambamba/sambamba-0.2.6_i386.deb
  - sudo dpkg -i sambamba-0.2.6_i386.deb
