language: ruby
rvm:
  - 1.9.2
  - 1.9.3
#  - jruby-19mode -- the same problems as with BioRuby, related to popen3
#  - rbx-19mode -- msgpack extension doesn't work with Rubinius

jdk:
  - oraclejdk7

before_install:
  - wget https://github.com/downloads/lomereiter/sambamba/sambamba-0.2.6_i386.deb
  - sudo dpkg -i sambamba-0.2.6_i386.deb
