require 'bio/command'
require 'oj'

require 'bio-sambamba/samheader.rb'
require 'bio-sambamba/alignment.rb'
require 'bio-sambamba/alignmentiterator.rb'
require 'bio-sambamba/bamfile.rb'
require 'bio-sambamba/samfile.rb'
require 'bio-sambamba/basepair.rb'
require 'bio-sambamba/filtering.rb'
